create table if not exists tb_user
(
    id             bigint                  not null
    primary key,
    username       varchar(255)            not null,
    email          varchar(100)            not null
    constraint tb_user_email_pk
    unique,
    password       varchar(60)             not null,
    avatar         varchar,
    create_user_id bigint                  not null,
    create_time    timestamp default now() not null,
    update_user_id bigint                  not null,
    update_time    timestamp default now() not null,
    del_flag       smallint                not null
    );

comment on table tb_user is '用户表';

comment on column tb_user.id is '用户id';

comment on column tb_user.username is '用户名';

comment on column tb_user.email is '邮箱';

comment on column tb_user.password is '用户密码';

comment on column tb_user.avatar is '用户头像';

comment on column tb_user.create_user_id is '创建人id';

comment on column tb_user.create_time is '创建时间';

comment on column tb_user.update_user_id is '更新人id';

comment on column tb_user.update_time is '更新时间';

comment on column tb_user.del_flag is '删除标识（0: 已删除，1：未删除）';

create table if not exists tb_role
(
    id          bigint                  not null
    primary key,
    role        varchar(60)             not null
    unique,
    create_time timestamp default now() not null,
    update_time timestamp default now() not null,
    remark      varchar
    );

comment on table tb_role is '角色表';

comment on column tb_role.id is '角色id';

comment on column tb_role.role is '角色信息';

comment on column tb_role.create_time is '创建时间';

comment on column tb_role.update_time is '更新时间';

comment on column tb_role.remark is '角色说明';

create table if not exists tb_permission
(
    id          bigint                  not null
    primary key,
    permission  varchar(60)             not null
    unique,
    create_time timestamp default now() not null,
    update_time timestamp default now() not null,
    remark      varchar
    );

comment on table tb_permission is '权限表';

comment on column tb_permission.permission is '权限信息';

comment on column tb_permission.create_time is '创建时间';

comment on column tb_permission.update_time is '更新时间';

comment on column tb_permission.remark is '权限说明';

create table if not exists tb_user_role
(
    id          bigint                  not null
    primary key,
    user_id     bigint                  not null,
    role_id     bigint                  not null,
    create_time timestamp default now() not null,
    update_time timestamp default now() not null
    );

comment on table tb_user_role is '用户角色关联表';

comment on column tb_user_role.id is '用户角色关联表id';

comment on column tb_user_role.user_id is '用户id';

comment on column tb_user_role.role_id is '角色id';

comment on column tb_user_role.create_time is '创建时间';

comment on column tb_user_role.update_time is '更新时间';

create table if not exists tb_role_permission
(
    id            bigint                  not null
    primary key,
    role_id       bigint                  not null,
    permission_id bigint                  not null,
    create_time   timestamp default now() not null,
    update_time   timestamp default now() not null
    );

comment on table tb_role_permission is '角色权限关联表';

comment on column tb_role_permission.id is '角色权限关联表id';

comment on column tb_role_permission.role_id is '角色id';

comment on column tb_role_permission.permission_id is '权限id';

comment on column tb_role_permission.create_time is '创建时间';

comment on column tb_role_permission.update_time is '更新时间';

create table if not exists tb_article
(
    id             bigint generated by default as identity
    primary key,
    title          varchar
    unique,
    content        varchar,
    state          smallint                not null,
    create_user_id bigint                  not null,
    create_time    timestamp default now() not null,
    update_user_id bigint                  not null,
    update_time    timestamp default now() not null,
    del_flag       smallint  default 1     not null,
    hot_flag       smallint  default 0     not null
    );

comment on table tb_article is '文章表';

comment on column tb_article.id is '文章id';

comment on column tb_article.title is '文章标题';

comment on column tb_article.content is '文章内容';

comment on column tb_article.state is '文章状态（0：草稿，1：已发布，）';

comment on column tb_article.create_user_id is '创建的用户id';

comment on column tb_article.create_time is '创建时间';

comment on column tb_article.update_user_id is '更新用户id';

comment on column tb_article.update_time is '更新时间';

comment on column tb_article.del_flag is '删除标识（0：未删除，1：已删除）';

comment on column tb_article.hot_flag is '热门文章（0：普通文章，1：推荐文章，2：热门文章）';

create table if not exists tb_tag
(
    id             bigint generated by default as identity
    primary key,
    name           varchar(255)               not null,
    color          varchar(255) default '#0000FF'::character varying,
    create_user_id bigint                     not null,
    create_time    timestamp    default now() not null,
    update_user_id bigint                     not null,
    update_time    timestamp                  not null
    );

comment on table tb_tag is '标签表';

comment on column tb_tag.id is '标签id';

comment on column tb_tag.name is '标签名称';

comment on column tb_tag.color is '标签颜色（十六进制类型）';

comment on column tb_tag.create_user_id is '创建人id';

comment on column tb_tag.create_time is '创建时间';

comment on column tb_tag.update_user_id is '修改人id';

comment on column tb_tag.update_time is '更新时间';

create table if not exists tb_article_tag
(
    id          bigint generated by default as identity
    primary key,
    article_id  bigint    not null,
    tag_id      bigint    not null,
    create_time timestamp not null,
    update_time timestamp not null
);

comment on table tb_article_tag is '文章标签关联表';

comment on column tb_article_tag.id is '文章标签关联id';

comment on column tb_article_tag.article_id is '文章id';

comment on column tb_article_tag.tag_id is '标签id';

comment on column tb_article_tag.create_time is '创建时间';

comment on column tb_article_tag.update_time is '更新时间';

create table if not exists tb_category
(
    id             bigint generated by default as identity
    primary key,
    name           varchar(255)               not null,
    color          varchar(255) default '#0000FF'::character varying,
    create_user_id bigint                     not null,
    create_time    timestamp    default now() not null,
    update_user_id bigint                     not null,
    update_time    timestamp                  not null
    );

comment on table tb_category is '类别表';

comment on column tb_category.color is '类别颜色（十六位进制）';

comment on column tb_category.create_user_id is '创建人id';

comment on column tb_category.create_time is '创建时间';

comment on column tb_category.update_user_id is '更新人id';

comment on column tb_category.update_time is '更新时间';

create table if not exists tb_article_category
(
    id          bigint generated by default as identity
    primary key,
    article_id  bigint                  not null,
    category_id bigint                  not null,
    create_time timestamp default now() not null,
    update_time timestamp               not null
    );

comment on table tb_article_category is '文章分类关联表';

comment on column tb_article_category.article_id is '文章id';

comment on column tb_article_category.category_id is '分类id';

comment on column tb_article_category.create_time is '创建时间';

comment on column tb_article_category.update_time is '更新时间';

create table if not exists tb_article_detail
(
    id          bigint generated by default as identity
    primary key,
    url         varchar(255)
    unique,
    article_id  bigint                  not null,
    create_time timestamp default now() not null,
    update_time timestamp               not null
    );

comment on table tb_article_detail is '文章详情表';

comment on column tb_article_detail.id is '文章详情表id';

comment on column tb_article_detail.url is '文章访问地址';

comment on column tb_article_detail.article_id is '文章id';

comment on column tb_article_detail.update_time is '更新时间';

create table if not exists tb_material
(
    id             bigint generated by default as identity
    constraint tb_file_material_pkey
    primary key,
    name           varchar                 not null,
    md5            varchar(255)
    constraint tb_file_material_md5_key
    unique,
    size           bigint                  not null,
    file_type      varchar(255)            not null,
    storage_type   varchar(255),
    url            varchar(255)            not null
    constraint tb_file_material_url_key
    unique,
    create_user_id bigint                  not null,
    create_time    timestamp default now() not null,
    update_user_id bigint                  not null,
    update_time    timestamp               not null,
    del_flag       smallint  default 1     not null
    );

comment on table tb_material is '文件素材表';

comment on column tb_material.id is '文件素材id';

comment on column tb_material.name is '文件名';

comment on column tb_material.md5 is '文件的md5值';

comment on column tb_material.size is '文件大小';

comment on column tb_material.file_type is '文件类型';

comment on column tb_material.storage_type is '文件存储类型';

comment on column tb_material.url is '文件地址';

comment on column tb_material.create_user_id is '创建人id';

comment on column tb_material.create_time is '创建时间';

comment on column tb_material.update_user_id is '更新人id';

comment on column tb_material.update_time is '更新时间';

comment on column tb_material.del_flag is '删除标识（0：已删除，1：未删除）';

create table if not exists sys_dict
(
    id          bigint generated by default as identity
    primary key,
    code        varchar(255)            not null
    unique,
    type        varchar(255)            not null,
    name        varchar(255),
    create_time timestamp default now() not null,
    update_time timestamp default now() not null
    );

comment on table sys_dict is '系统字典表';

comment on column sys_dict.id is '系统字典表id';

comment on column sys_dict.code is '字典Code码';

comment on column sys_dict.type is '编码类型';

comment on column sys_dict.name is '编码名称';

comment on column sys_dict.create_time is '创建时间';

comment on column sys_dict.update_time is '更新时间';

create table if not exists tb_article_material
(
    id          bigserial
    primary key,
    article_id  bigint,
    material_id bigint,
    create_time timestamp with time zone,
    update_time timestamp with time zone
);

comment on table tb_article_material is '文章素材关联表';

comment on column tb_article_material.id is '文件素材关联id';

comment on column tb_article_material.article_id is '文章id';

comment on column tb_article_material.material_id is '素材id';

comment on column tb_article_material.create_time is '创建时间';

comment on column tb_article_material.update_time is '更新时间';