CREATE TABLE "tb_article" (
	-- 文章id
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 文章标题
	"title" VARCHAR UNIQUE,
	-- 文章内容
	"content" VARCHAR,
	-- 文章状态（0：草稿，1：已发布，）
	"state" SMALLINT NOT NULL,
	-- 创建的用户id
	"create_user_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 更新用户id
	"update_user_id" BIGINT NOT NULL,
	-- 更新时间
	"update_time" DATE NOT NULL,
	-- 删除标识（0：未删除，1：已删除）
	"del_flag" SMALLINT NOT NULL DEFAULT 1,
	-- 热门文章（0：普通文章，1：推荐文章，2：热门文章）
	"hot_flag" SMALLINT NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_article" IS '文章表';
COMMENT ON COLUMN tb_article.id IS '文章id';
COMMENT ON COLUMN tb_article.title IS '文章标题';
COMMENT ON COLUMN tb_article.content IS '文章内容';
COMMENT ON COLUMN tb_article.state IS '文章状态（0：草稿，1：已发布，）';
COMMENT ON COLUMN tb_article.create_user_id IS '创建的用户id';
COMMENT ON COLUMN tb_article.create_time IS '创建时间';
COMMENT ON COLUMN tb_article.update_user_id IS '更新用户id';
COMMENT ON COLUMN tb_article.update_time IS '更新时间';
COMMENT ON COLUMN tb_article.del_flag IS '删除标识（0：未删除，1：已删除）';
COMMENT ON COLUMN tb_article.hot_flag IS '热门文章（0：普通文章，1：推荐文章，2：热门文章）';


CREATE TABLE "tb_tag" (
	-- 标签id
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 标签名称
	"name" VARCHAR(255) NOT NULL,
	-- 标签颜色（十六进制类型）
	"color" VARCHAR(255) DEFAULT '#0000FF',
	-- 创建人id
	"create_user_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 修改人id
	"update_user_id" BIGINT NOT NULL,
	-- 更新时间
	"update_time" DATE NOT NULL,
	-- 删除标识（0：已删除，1：未删除）
	"del_flag" SMALLINT NOT NULL DEFAULT 1,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_tag" IS '标签表';
COMMENT ON COLUMN tb_tag.id IS '标签id';
COMMENT ON COLUMN tb_tag.name IS '标签名称';
COMMENT ON COLUMN tb_tag.color IS '标签颜色（十六进制类型）';
COMMENT ON COLUMN tb_tag.create_user_id IS '创建人id';
COMMENT ON COLUMN tb_tag.create_time IS '创建时间';
COMMENT ON COLUMN tb_tag.update_user_id IS '修改人id';
COMMENT ON COLUMN tb_tag.update_time IS '更新时间';
COMMENT ON COLUMN tb_tag.del_flag IS '删除标识（0：已删除，1：未删除）';


CREATE TABLE "tb_article_tag" (
	-- 文章标签关联id
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 文章id
	"article_id" BIGINT NOT NULL,
	-- 标签id
	"tag_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL,
	-- 更新时间
	"update_time" DATE NOT NULL,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_article_tag" IS '文章标签关联表';
COMMENT ON COLUMN tb_article_tag.id IS '文章标签关联id';
COMMENT ON COLUMN tb_article_tag.article_id IS '文章id';
COMMENT ON COLUMN tb_article_tag.tag_id IS '标签id';
COMMENT ON COLUMN tb_article_tag.create_time IS '创建时间';
COMMENT ON COLUMN tb_article_tag.update_time IS '更新时间';


CREATE TABLE "tb_category" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	-- 类别颜色（十六位进制）
	"color" VARCHAR(255) DEFAULT '#0000FF',
	-- 创建人id
	"create_user_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 更新人id
	"update_user_id" BIGINT NOT NULL,
	-- 更新时间
	"update_time" DATE NOT NULL,
	-- 删除标识（0：已删除，1：未删除）
	"del_flag" SMALLINT NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_category" IS '类别表';
COMMENT ON COLUMN tb_category.color IS '类别颜色（十六位进制）';
COMMENT ON COLUMN tb_category.create_user_id IS '创建人id';
COMMENT ON COLUMN tb_category.create_time IS '创建时间';
COMMENT ON COLUMN tb_category.update_user_id IS '更新人id';
COMMENT ON COLUMN tb_category.update_time IS '更新时间';
COMMENT ON COLUMN tb_category.del_flag IS '删除标识（0：已删除，1：未删除）';


CREATE TABLE "tb_article_category" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 文章id
	"article_id" BIGINT NOT NULL,
	-- 分类id
	"category_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 更新时间
	"update_time" DATE NOT NULL,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_article_category" IS '文章分类关联表';
COMMENT ON COLUMN tb_article_category.article_id IS '文章id';
COMMENT ON COLUMN tb_article_category.category_id IS '分类id';
COMMENT ON COLUMN tb_article_category.create_time IS '创建时间';
COMMENT ON COLUMN tb_article_category.update_time IS '更新时间';


CREATE TABLE "tb_article_detail" (
	-- 文章详情表id
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 文章访问地址
	"url" VARCHAR(255) UNIQUE,
	-- 文章id
	"article_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 更新时间
	"update_time" DATE NOT NULL,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_article_detail" IS '文章详情表';
COMMENT ON COLUMN tb_article_detail.id IS '文章详情表id';
COMMENT ON COLUMN tb_article_detail.url IS '文章访问地址';
COMMENT ON COLUMN tb_article_detail.article_id IS '文章id';
COMMENT ON COLUMN tb_article_detail.cerate_time IS '创建时间';
COMMENT ON COLUMN tb_article_detail.update_time IS '更新时间';


CREATE TABLE "tb_file_material" (
	-- 文件素材id
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 文件名
	"name" VARCHAR NOT NULL,
	-- 文件的md5值
	"md5" VARCHAR(255) UNIQUE,
	-- 文件大小
	"size" VARCHAR(255) NOT NULL,
	-- 文件类型Code
	"file_type_code" VARCHAR(255) NOT NULL,
	-- 文件存储类型Code
	"storage_type_code" VARCHAR(255),
	-- 文件地址
	"url" VARCHAR(255) NOT NULL UNIQUE,
	-- 创建人id
	"create_user_id" BIGINT NOT NULL,
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 更新人id
	"update_user_id" BIGINT NOT NULL,
	-- 更新时间
	"update_time" DATE NOT NULL,
	-- 删除标识（0：已删除，1：未删除）
	"del_flag" SMALLINT NOT NULL DEFAULT 1,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "tb_file_material" IS '文件素材表';
COMMENT ON COLUMN tb_file_material.id IS '文件素材id';
COMMENT ON COLUMN tb_file_material.name IS '文件名';
COMMENT ON COLUMN tb_file_material.md5 IS '文件的md5值';
COMMENT ON COLUMN tb_file_material.size IS '文件大小';
COMMENT ON COLUMN tb_file_material.file_type_code IS '文件类型Code';
COMMENT ON COLUMN tb_file_material.storage_type_code IS '文件存储类型Code';
COMMENT ON COLUMN tb_file_material.url IS '文件地址';
COMMENT ON COLUMN tb_file_material.create_user_id IS '创建人id';
COMMENT ON COLUMN tb_file_material.create_time IS '创建时间';
COMMENT ON COLUMN tb_file_material.update_user_id IS '更新人id';
COMMENT ON COLUMN tb_file_material.update_time IS '更新时间';
COMMENT ON COLUMN tb_file_material.del_flag IS '删除标识（0：已删除，1：未删除）';


CREATE TABLE "sys_dict" (
	-- 系统字典表id
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 字典Code码
	"code" VARCHAR(255) NOT NULL UNIQUE,
	-- 编码类型
	"type" VARCHAR(255) NOT NULL,
	-- 编码名称
	"name" VARCHAR(255),
	-- 创建时间
	"create_time" DATE NOT NULL DEFAULT NOW(),
	-- 更新时间
	"update_time" DATE NOT NULL,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "sys_dict" IS '系统字典表';
COMMENT ON COLUMN sys_dict.id IS '系统字典表id';
COMMENT ON COLUMN sys_dict.code IS '字典Code码';
COMMENT ON COLUMN sys_dict.type IS '编码类型';
COMMENT ON COLUMN sys_dict.name IS '编码名称';
COMMENT ON COLUMN sys_dict.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict.update_time IS '更新时间';

